Added first Gambling command (coinflip)
Daniele122898/SoraBot-v2 pull request #103
Opened 2020-02-17 21:28 UTC by TimmmyGotPasion

The coinflip command works like this:
 $coinflip 20 heads
 $coinflip amountToBet CoinSize

If you bet correctly you well get amoutToBet * 2
else you loose amountToBet.

Dont expect clean code haha...

2020-02-18 08:46 UTC, Daniele122898 commented
For completeness sake i will post my answer from discord here

im sorry i cant accept that pull request
1. Dont commit ur migrations. that shit is already fucked up so pls do not push those
2. What u have as a service does not need to be a service. It does not store anything or does anything that must be persistant. The reason for services is bcs modules are not persistant. they get created on command and then removed again. they are "scoped". Services are signletons bcs they use stuff that should be persistant or only initialized once for performance
3. Your module initialized things it doesnt need. Also you introduced multiple memory leaks since you dont dispose of any disposable objects u created. Like the sora context etc. pls use using for that
Since sora is already a mess bcs of old shit code i wrote back when i didnt know shit i dont wanna make it worse. So i'll only merge once all those issues are corrected :heart:

2020-02-18 17:48 UTC, sn0w commented on SoraBot-v2/SoraBot-v2/Module/GamblingModule.cs
> +        }
You can shorten this method to

```cs
public int GetResult(string side)
{
    Random random = new Random();
    return string.Equals(
        side,
        random.Next(100) % 2 == 0 ? "heads" : "tails",
        StringComparison.InvariantCultureIgnoreCase
    );
}
```

or even get rid of the helper altogether and just add this one-liner to the `FlipCoin` method.

2020-02-18 17:49 UTC, ghost requested changes

2020-02-18 17:49 UTC, sn0w commented on SoraBot-v2/SoraBot-v2/Module/GamblingModule.cs
> +    }
You can shorten this method to

```cs
public int GetResult(string side)
{
    Random random = new Random();
    return string.Equals(
        side,
        random.Next(100) % 2 == 0 ? "heads" : "tails",
        StringComparison.InvariantCultureIgnoreCase
    );
}
```

or even get rid of the helper altogether and just add this one-liner to the `FlipCoin` method.

2020-02-20 21:45 UTC, ghost approved these changes

2020-02-20 21:47 UTC, merged